### PR TITLE
Ability to set a path to scan

### PR DESCRIPTION
**Pull request by JSCProjects**
If you scan a specific directory than it's easier to identify(and delete) your composition assemblies

### CODE REVIEW

**Comment by mauroservienti** [comment]
@JSCProjects thanks for raising this. I'm travelling right now, I'll have a look soon.

**Comment by mauroservienti** [comment]
If the reason for choosing a specific directory, other then the default output directory, is to simplify identification and deletion; given that it possibile to change the scanner behavior from searching `TopDirectoryOnly` to `AllDirectories`, composition assemblies can be stored in a directory below the output one. Is that enough?

**Comment by JSCProjects** [comment]
@mauroservienti Ok that's also ok. 

I was looking for a way to deploy ViewModelComposition packages from different services into a specific directory from a zipped file, but when I started doing that I got some troubles with (nuget)references who aren't copied to the output directory and therefore missing in the zip. Also DI/IOC is also difficult this way. So I dropped the zip and made my ViewModelComposition packages available as an NuGet package and reference them in my WebHost and did the DI/IOC then. It's not perfect but for now it feels ok/manageable.

**Comment by mauroservienti** [comment]
Closing for now. Feel free to re-open if anything comes up.

**Pull request closed without merging**
